import { DatabaseSync } from 'node:sqlite';
const columns={user_id:"VARCHAR(191) NOT NULL DEFAULT ''",instance_id:"VARCHAR(191) NOT NULL DEFAULT ''",record_status:"VARCHAR(32) NOT NULL DEFAULT ''",created_at:"BIGINT NOT NULL DEFAULT 0",due_at:"BIGINT NOT NULL DEFAULT 0",lookup_key:"VARCHAR(254) NOT NULL DEFAULT ''",metadata_version:'INT NOT NULL DEFAULT 0'};
const indexes={zelon_owner:['namespace','user_id','created_at','record_key'],zelon_instance:['namespace','instance_id','created_at','record_key'],zelon_due:['namespace','record_status','due_at'],zelon_instance_due:['namespace','instance_id','record_status','due_at'],zelon_lookup:['namespace','lookup_key']};
const metadata=v=>[v.userId||'',v.instanceId||'',v.status||'',Date.parse(v.createdAt||'')||0,v.sendAt??v.nextAt??v.expires??0,v.email?.toLowerCase()||'',1];
export async function openStore() {
 let db,pool,lease,leaseLost=false;
 const execute=async(sql,args=[])=>pool?(await pool.query(sql,args))[0]:db.prepare(sql).all(...args);
 const mutate=async(sql,args=[])=>pool?(await pool.query(sql,args))[0]:db.prepare(sql).run(...args);
 try {
  if(process.env.MYSQL_HOST){const mysql=await import('mysql2/promise');pool=mysql.createPool({host:process.env.MYSQL_HOST,port:Number(process.env.MYSQL_PORT||3306),user:process.env.MYSQL_USER,password:process.env.MYSQL_PASSWORD,database:process.env.MYSQL_DATABASE,connectionLimit:10,charset:'utf8mb4',...(process.env.MYSQL_SSL==='true'?{ssl:{rejectUnauthorized:true}}:{})});lease=await pool.getConnection();lease.on('error',()=>{leaseLost=true;});const [locks]=await lease.query("SELECT GET_LOCK(CONCAT('zelon:',LEFT(SHA2(DATABASE(),256),56)), 0) AS acquired");if(!locks[0].acquired)throw Error('Another Zelon server is using this database; run one process');await pool.query('CREATE TABLE IF NOT EXISTS zelon_records(namespace VARCHAR(64) NOT NULL,record_key VARCHAR(191) NOT NULL,payload LONGTEXT NOT NULL,PRIMARY KEY(namespace,record_key))');}
  else{if(process.env.NODE_ENV==='production')throw Error('Production requires MYSQL_HOST and persistent MySQL database');db=new DatabaseSync(process.env.SQLITE_PATH||'zelon.sqlite');db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS zelon_records(namespace TEXT NOT NULL,record_key TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(namespace,record_key))');}
  const existing=pool?(await execute("SELECT COLUMN_NAME AS name FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='zelon_records'")):db.prepare('PRAGMA table_info(zelon_records)').all();
  for(const [name,definition] of Object.entries(columns))if(!existing.some(c=>c.name===name))await mutate(`ALTER TABLE zelon_records ADD COLUMN ${name} ${pool?definition:definition.replace(/VARCHAR\(\d+\)/,'TEXT')}`);
  const existingIndexes=pool?await execute("SELECT DISTINCT INDEX_NAME AS name FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='zelon_records'"):db.prepare('PRAGMA index_list(zelon_records)').all();
  for(const [name,cols]of Object.entries(indexes))if(!existingIndexes.some(i=>i.name===name))await mutate(`CREATE INDEX ${name} ON zelon_records(${cols.join(',')})`);
  let rows;do{rows=await execute('SELECT namespace,record_key,payload FROM zelon_records WHERE metadata_version=0 LIMIT 500');for(const row of rows)await mutate(`UPDATE zelon_records SET ${Object.keys(columns).map(c=>c+'=?').join(',')} WHERE namespace=? AND record_key=?`,[...metadata(JSON.parse(row.payload)),row.namespace,row.record_key]);}while(rows.length);
 }catch(error){if(lease)lease.release();if(pool)await pool.end();if(db)db.close();throw error;}
 function healthy(){if(leaseLost)throw Error('Database worker lease lost; restart the server before processing requests');}
 const colnames=['namespace','record_key','payload',...Object.keys(columns)];
 const store={
  async get(ns,key){healthy();const rows=await execute('SELECT payload FROM zelon_records WHERE namespace=? AND record_key=?',[ns,key]);return rows[0]?JSON.parse(rows[0].payload):null;},
  async query(ns,{userId,instanceId,status,email,limit=100,before,beforeKey='',dueBefore,ascending=false}={}){healthy();if(!Number.isInteger(limit)||limit<1||limit>1000)throw Error('Query limit must be between 1 and 1000');const clauses=['namespace=?'],args=[ns];for(const [column,value]of [['user_id',userId],['instance_id',instanceId],['record_status',status],['lookup_key',email?.toLowerCase()]])if(value!==undefined){clauses.push(column+'=?');args.push(value);}if(dueBefore!==undefined){clauses.push('due_at<=?');args.push(dueBefore);}if(before!==undefined){clauses.push('(created_at<? OR (created_at=? AND record_key<?))');args.push(before,before,beforeKey);}const order=ascending?'ASC':'DESC';return(await execute(`SELECT payload FROM zelon_records WHERE ${clauses.join(' AND ')} ORDER BY created_at ${order},record_key ${order} LIMIT ${limit}`,args)).map(r=>JSON.parse(r.payload));},
  async all(ns){healthy();return(await execute('SELECT payload FROM zelon_records WHERE namespace=?',[ns])).map(r=>JSON.parse(r.payload));},
  async set(ns,key,v){healthy();const args=[ns,key,JSON.stringify(v),...metadata(v)];const update=colnames.slice(2).map(c=>`${c}=${pool?'VALUES('+c+')':'excluded.'+c}`).join(',');await mutate(`INSERT INTO zelon_records(${colnames.join(',')}) VALUES(${colnames.map(()=>'?').join(',')}) ${pool?'ON DUPLICATE KEY UPDATE':'ON CONFLICT(namespace,record_key) DO UPDATE SET'} ${update}`,args);},
  async insert(ns,key,v){healthy();const args=[ns,key,JSON.stringify(v),...metadata(v)];const result=await mutate(`INSERT ${pool?'IGNORE ':''}INTO zelon_records(${colnames.join(',')}) VALUES(${colnames.map(()=>'?').join(',')}) ${pool?'':'ON CONFLICT(namespace,record_key) DO NOTHING'}`,args);return pool?result.affectedRows===1:result.changes===1;},
  async transition(ns,key,expected,v){healthy();const fields=['payload',...Object.keys(columns)];const result=await mutate(`UPDATE zelon_records SET ${fields.map(c=>c+'=?').join(',')} WHERE namespace=? AND record_key=? AND record_status=?`,[JSON.stringify(v),...metadata(v),ns,key,expected]);return pool?result.affectedRows===1:result.changes===1;},
  async clearNamespace(ns){healthy();await mutate('DELETE FROM zelon_records WHERE namespace=?',[ns]);},
  async delete(ns,key){healthy();await mutate('DELETE FROM zelon_records WHERE namespace=? AND record_key=?',[ns,key]);},
  async health(){healthy();if(pool){const [rows]=await lease.query("SELECT IS_USED_LOCK(CONCAT('zelon:',LEFT(SHA2(DATABASE(),256),56)))=CONNECTION_ID() AS held");if(!rows[0].held){leaseLost=true;throw Error('Database lease is not held');}}else db.prepare('SELECT 1').get();},
  async close(){if(pool){try{await lease.query("SELECT RELEASE_LOCK(CONCAT('zelon:',LEFT(SHA2(DATABASE(),256),56)))");}catch{}lease.release();await pool.end();}else db.close();}
 };return store;
}
